# Generated by Django 5.0.4 on 2024-04-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Judgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.TextField(max_length=50)),
                ("level", models.CharField(max_length=1)),
                ("problem_id", models.TextField(max_length=5)),
                ("correct", models.CharField(max_length=1)),
            ],
        ),
    ]
